#!/usr/bin/env node
// function run_cmd(cmd, args, callBack ) {
//   var spawn = require('child_process').spawn;
//   var child = spawn(cmd, args);
//   var resp = "";
//
//   child.stdout.on('data', function (buffer) { resp += buffer.toString() });
//   child.stdout.on('end', function() { callBack (resp) });
// } // ()

var sys = require('sys')
var exec = require('child_process').exec;
function puts(error, stdout, stderr) { sys.puts(stdout) }
exec("PYTHONPATH=. DJANGO_SETTINGS_MODULE=testsite.settings python testsite/tornado_main.py", puts);

// run_cmd( "PYTHONPATH=. DJANGO_SETTINGS_MODULE=testsite.settings python", ["testsite/tornado_main.py"], function(text) { console.log (text) });



require("./jankey");
